In [1]:
import numpy as np
import tensorflow as tf

In [9]:
mask = np.random.randint(0,2,size=[3,10,10]).astype(np.bool)

In [10]:
print(mask)

[[[ True  True  True  True False False  True False  True False]
  [ True False  True False  True False False  True  True False]
  [False  True  True  True  True  True  True  True  True  True]
  [False  True  True False False  True  True  True  True  True]
  [ True False  True False  True False False  True  True  True]
  [False False  True  True  True  True  True  True False  True]
  [ True False False  True False  True False  True  True False]
  [ True  True  True  True  True  True False False  True  True]
  [False  True False False False False False  True  True  True]
  [False False  True False  True  True False False False False]]

 [[False  True  True  True False  True False  True False False]
  [False  True False False False False  True  True False  True]
  [False  True False  True False  True  True False  True False]
  [ True  True  True  True False False False False False False]
  [False False False  True  True False  True False  True  True]
  [ True False False False  True  True

In [7]:
data = np.reshape(np.arange(0,3*10*10*2),[3,10,10,2])

In [13]:
print(data)

[[[[  0   1]
   [  2   3]
   [  4   5]
   [  6   7]
   [  8   9]
   [ 10  11]
   [ 12  13]
   [ 14  15]
   [ 16  17]
   [ 18  19]]

  [[ 20  21]
   [ 22  23]
   [ 24  25]
   [ 26  27]
   [ 28  29]
   [ 30  31]
   [ 32  33]
   [ 34  35]
   [ 36  37]
   [ 38  39]]

  [[ 40  41]
   [ 42  43]
   [ 44  45]
   [ 46  47]
   [ 48  49]
   [ 50  51]
   [ 52  53]
   [ 54  55]
   [ 56  57]
   [ 58  59]]

  [[ 60  61]
   [ 62  63]
   [ 64  65]
   [ 66  67]
   [ 68  69]
   [ 70  71]
   [ 72  73]
   [ 74  75]
   [ 76  77]
   [ 78  79]]

  [[ 80  81]
   [ 82  83]
   [ 84  85]
   [ 86  87]
   [ 88  89]
   [ 90  91]
   [ 92  93]
   [ 94  95]
   [ 96  97]
   [ 98  99]]

  [[100 101]
   [102 103]
   [104 105]
   [106 107]
   [108 109]
   [110 111]
   [112 113]
   [114 115]
   [116 117]
   [118 119]]

  [[120 121]
   [122 123]
   [124 125]
   [126 127]
   [128 129]
   [130 131]
   [132 133]
   [134 135]
   [136 137]
   [138 139]]

  [[140 141]
   [142 143]
   [144 145]
   [146 147]
   [148 149]
   [150 151

In [11]:
data_filter = data[mask]

In [12]:
print(data_filter)

[[  0   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [ 12  13]
 [ 16  17]
 [ 20  21]
 [ 24  25]
 [ 28  29]
 [ 34  35]
 [ 36  37]
 [ 42  43]
 [ 44  45]
 [ 46  47]
 [ 48  49]
 [ 50  51]
 [ 52  53]
 [ 54  55]
 [ 56  57]
 [ 58  59]
 [ 62  63]
 [ 64  65]
 [ 70  71]
 [ 72  73]
 [ 74  75]
 [ 76  77]
 [ 78  79]
 [ 80  81]
 [ 84  85]
 [ 88  89]
 [ 94  95]
 [ 96  97]
 [ 98  99]
 [104 105]
 [106 107]
 [108 109]
 [110 111]
 [112 113]
 [114 115]
 [118 119]
 [120 121]
 [126 127]
 [130 131]
 [134 135]
 [136 137]
 [140 141]
 [142 143]
 [144 145]
 [146 147]
 [148 149]
 [150 151]
 [156 157]
 [158 159]
 [162 163]
 [174 175]
 [176 177]
 [178 179]
 [184 185]
 [188 189]
 [190 191]
 [202 203]
 [204 205]
 [206 207]
 [210 211]
 [214 215]
 [222 223]
 [232 233]
 [234 235]
 [238 239]
 [242 243]
 [246 247]
 [250 251]
 [252 253]
 [256 257]
 [260 261]
 [262 263]
 [264 265]
 [266 267]
 [286 287]
 [288 289]
 [292 293]
 [296 297]
 [298 299]
 [300 301]
 [308 309]
 [310 311]
 [312 313]
 [316 317]
 [324 325]
 [326 327]
 [332 333]