In [1]:
import numpy as np
import tensorflow as tf

In [3]:
grid_y = np.reshape(np.arange(0,grid_shape[0]),[-1,1,1,1])

In [18]:
print(np.random.randint.__doc__)


        randint(low, high=None, size=None, dtype='l')

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete uniform" distribution of
        the specified dtype in the "half-open" interval [`low`, `high`). If
        `high` is None (the default), then results are from [0, `low`).

        Parameters
        ----------
        low : int
            Lowest (signed) integer to be drawn from the distribution (unless
            ``high=None``, in which case this parameter is the *highest* such
            integer).
        high : int, optional
            If provided, one above the largest (signed) integer to be drawn
            from the distribution (see above for behavior if ``high=None``).
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  Default is None, in which case a
            single value 

In [5]:
grid_y = np.tile(grid_y,[1,grid_shape[1],1,1])

In [16]:
print(grid_y.shape)

(13, 26, 1, 1)


In [10]:
grid_x = np.tile(np.reshape(np.arange(0,grid_shape[1]),[1,-1,1,1]),[grid_shape[0],1,1,1])

In [11]:
print(grid_x)

[[[[ 0]]

  [[ 1]]

  [[ 2]]

  [[ 3]]

  [[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]

  [[ 8]]

  [[ 9]]

  [[10]]

  [[11]]

  [[12]]

  [[13]]

  [[14]]

  [[15]]

  [[16]]

  [[17]]

  [[18]]

  [[19]]

  [[20]]

  [[21]]

  [[22]]

  [[23]]

  [[24]]

  [[25]]]


 [[[ 0]]

  [[ 1]]

  [[ 2]]

  [[ 3]]

  [[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]

  [[ 8]]

  [[ 9]]

  [[10]]

  [[11]]

  [[12]]

  [[13]]

  [[14]]

  [[15]]

  [[16]]

  [[17]]

  [[18]]

  [[19]]

  [[20]]

  [[21]]

  [[22]]

  [[23]]

  [[24]]

  [[25]]]


 [[[ 0]]

  [[ 1]]

  [[ 2]]

  [[ 3]]

  [[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]

  [[ 8]]

  [[ 9]]

  [[10]]

  [[11]]

  [[12]]

  [[13]]

  [[14]]

  [[15]]

  [[16]]

  [[17]]

  [[18]]

  [[19]]

  [[20]]

  [[21]]

  [[22]]

  [[23]]

  [[24]]

  [[25]]]


 [[[ 0]]

  [[ 1]]

  [[ 2]]

  [[ 3]]

  [[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]

  [[ 8]]

  [[ 9]]

  [[10]]

  [[11]]

  [[12]]

  [[13]]

  [[14]]

  [[15]]

  [[16]]

  [[17]]

  [[18]]

  [[19]]

  [[20]]

  [[

In [12]:
print(grid_x.shape)

(13, 26, 1, 1)


In [13]:
print(grid_y.shape)

(13, 26, 1, 1)


In [14]:
print(np.concatenate([grid_x,grid_y],axis=-1))

[[[[ 0  0]]

  [[ 1  0]]

  [[ 2  0]]

  [[ 3  0]]

  [[ 4  0]]

  [[ 5  0]]

  [[ 6  0]]

  [[ 7  0]]

  [[ 8  0]]

  [[ 9  0]]

  [[10  0]]

  [[11  0]]

  [[12  0]]

  [[13  0]]

  [[14  0]]

  [[15  0]]

  [[16  0]]

  [[17  0]]

  [[18  0]]

  [[19  0]]

  [[20  0]]

  [[21  0]]

  [[22  0]]

  [[23  0]]

  [[24  0]]

  [[25  0]]]


 [[[ 0  1]]

  [[ 1  1]]

  [[ 2  1]]

  [[ 3  1]]

  [[ 4  1]]

  [[ 5  1]]

  [[ 6  1]]

  [[ 7  1]]

  [[ 8  1]]

  [[ 9  1]]

  [[10  1]]

  [[11  1]]

  [[12  1]]

  [[13  1]]

  [[14  1]]

  [[15  1]]

  [[16  1]]

  [[17  1]]

  [[18  1]]

  [[19  1]]

  [[20  1]]

  [[21  1]]

  [[22  1]]

  [[23  1]]

  [[24  1]]

  [[25  1]]]


 [[[ 0  2]]

  [[ 1  2]]

  [[ 2  2]]

  [[ 3  2]]

  [[ 4  2]]

  [[ 5  2]]

  [[ 6  2]]

  [[ 7  2]]

  [[ 8  2]]

  [[ 9  2]]

  [[10  2]]

  [[11  2]]

  [[12  2]]

  [[13  2]]

  [[14  2]]

  [[15  2]]

  [[16  2]]

  [[17  2]]

  [[18  2]]

  [[19  2]]

  [[20  2]]

  [[21  2]]

  [[22  2]]

  [[23  2]]

  [[24  

In [ ]:
print(gri)

In [6]:
var = tf.Variable(np.random.randint(0,20,size=[3,4]))

In [8]:
print(var[:,0])

Tensor("strided_slice_1:0", shape=(3,), dtype=int32)


In [2]:
grid_shape=[13,13]
grid_y = np.arange(0,grid_shape[0])
grid_x = np.arange(0,grid_shape[1])
grid_x,grid_y = np.meshgrid(grid_x,grid_y)
grid = np.stack([grid_x,grid_y],axis=-1)
grid = np.expand_dims(grid,axis=2)

In [3]:
from keras import backend as K

Using TensorFlow backend.


In [57]:
session = K.get_session()

In [4]:
feats = K.constant(np.ones(shape=[30,13,13,256]))

In [5]:
grid_shape = K.shape(feats)
grid_y = K.arange(0,grid_shape[0])
grid_y = K.expand_dims(grid_y,axis=1)
grid_y = K.tile(grid_y,[1,grid_shape[1]])

grid_x = K.arange(0,grid_shape[1])
grid_x = K.expand_dims(grid_x,axis=0)
grid_x = K.tile(grid_x,[grid_shape[0],1])

grid = K.stack((grid_x,grid_y),axis=-1)
grid = K.expand_dims(grid,axis=2)

In [6]:
print(grid)

Tensor("ExpandDims_2:0", shape=(?, ?, 1, 2), dtype=int32)


In [59]:
result = session.run(grid)
print(result.shape)

(30, 13, 1, 2)


In [8]:
print(5/3)

1.6666666666666667


In [46]:
print(grid)

Tensor("ExpandDims_3:0", shape=(?, 0, 1, 2), dtype=int32)


In [36]:
print(grid_shape)

Tensor("strided_slice:0", shape=(2,), dtype=int32)


In [38]:
K.meshgrid.__doc__

AttributeError: module 'keras.backend' has no attribute 'meshgrid'

In [35]:
print(grid)

Tensor("Cast:0", shape=(?, ?, 1, 2), dtype=float32)
